import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import AuthProvider from '../components/AuthProvider';
import Box from '@mui/material/Box';
import Navbar from '@/components/Navbar';
import '../assets/css/layout.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Grant Management | UWGK',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/images/UW_Social_Circle-32x32.png"
          sizes="32x32"
        ></link>
        <link
          rel="icon"
          href="/images/UW_Social_Circle-192x192.png"
          sizes="192x192"
        ></link>
      </head>
      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <Box
            sx={{
              margin: '0',
              height: '100vh',
              boxSizing: 'border-box',
              paddingTop: '5rem',
            }}
          >
            {children}
          </Box>
        </AuthProvider>
      </body>
    </html>
  );
}
